### ISSUE TITLE
Data analysis of current bounties

### ISSUE THREAD

**Issue by andytudhope** [status-im/ETHPrize-interviews#14]
We need someone with a background in NLP and data analysis to help us parse the massive amount of data we have gathered in the course of these interviews and produce all of the information-at-a-glance that will live on the home page of our Interview Report (for which there is a design bounty currently out).

We want to see word clouds, graphs, and any other visual tool that will make it easy for people to grasp the most salient points without needing to go through in detail every single interview.

cc @jpbowen for some further potential requirements/ideas about how and what we should be looking to pull from the report.

Much like the design bounty - if you are keen to do this, please let us know in a comment below with a little blurb about who you are and what qualifies you to do this and we will lock the bounty for the person we feel is capable of doing it to a world-class standard.

Both nvivo and deedose were designed for exactly this type of task. Although both are proprietary with trial periods if someone wants to crank out an analysis in a few days. For a more secure workspace, nvivo is probably the way to go since you download a local copy. Beyond that the true open source is to get your hands dirty with R/Rstudio and text analysis package like RQDA.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x3ce86d721ccc609ec7a24af9a509bb6a8382cb6cb36989e51e99e81f2eb510f9](https://etherscan.io/tx/0x3ce86d721ccc609ec7a24af9a509bb6a8382cb6cb36989e51e99e81f2eb510f9)

**Comment by mkosowsk** [comment]
@CS76 we are still processing a few of the newest interviews, but this is almost all the way up-to-date :) is this correct @andytudhope? 🤔

**Comment by andytudhope** [comment]
Yeah. And I have found a data scientist in France to help handle this, thanks. It would be awesome to have some help with building the actual report for web and stuff though @CS76

**Comment by CS76** [comment]
Wonderful! Would be great if we can have something link a Kaggle kernel (https://www.kaggle.com/kernels) so the community could extend and make necessary changes :) Thanks

**Comment by andytudhope** [comment]
Ask and you shall receive @CS76 https://www.kaggle.com/cryptowanderer/ethprize-developer-interviews

**Comment by andytudhope** [comment]
@CS76 https://www.kaggle.com/mratsim/state-of-the-art-nlp-on-ethereum-dev-interviews

**Comment by mratsim** [comment]
Wow so fast, I didn't even have time!

**Comment by CS76** [comment]
Awesome! community-driven open source innovation at its best

**Comment by mratsim** [comment]
I've updated the kernel - https://www.kaggle.com/mratsim/state-of-the-art-nlp-on-ethereum-dev-interviews

Some thoughts on the automated processing:

  - Currently Kaggle doesn't wrap properly and part of the text is cut :/
  - I need a prettier WordCloud Generator, [some inspiration here.](http://minimaxir.com/2016/05/wordclouds/)
![image](https://user-images.githubusercontent.com/22738317/40989903-883024fe-68ef-11e8-9c5b-ec59acec80a3.png)
![image](https://user-images.githubusercontent.com/22738317/40989921-92e64dc4-68ef-11e8-94ff-0ea9e92b3244.png)
  - I'm not satisfied with the current topic modelling, as a second step I'm thinking of a model picking "quotes" from each topic and having them displayed (wordcloud again?), especially  for "who I am and what am I working on?"

In any case, I think like currently automated processing is not good enough due to some super niche questions (Ethereum dev tools) and I will instead do more manual tagging, maybe separate in an "automated" and a manual analysis.

**Comment by mratsim** [comment]
For the final report, due to the complexity and accuracy issue of automated approaches, what is presented on the website was a classification/tagging by topics and projects made by @andytudhope : [ETHPrize report](http://ethprize.io/).

However as data to analyze grows, it's good to have a set of NLP approaches that we can refine.

I've added some more approaches in [status-im/datasets](https://github.com/status-im/datasets/tree/master/201807_ETHPrize).

- A simple word frequency count based on the topics/projects chosen.
- A WIP semi-supervised approach, i.e. helping/shortcuting the learning by telling the model which words to focus on.
